baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sophia Zhukovsky'
theme = 'light-bi-hugo'

# theme settings
# https://github.com/binokochumolvarghese/lightbi-hugo/wiki/Theme-Parameters
homepageLayout = "profile"
profileShortbio = "short bio"
profilePhoto = "assets/img/profile/home-profile-pic.jpg"
